id: I337CB8FB
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:52:10.164887
last_modified: 2023-02-09 14:52:10.165000
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: zh
bases:
  '3903':
    base_file: 3903.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
